(function(){
'use strict'; const PS=window.PS,U=PS.Utils;
class AISystem{
  constructor(engine){this.engine=engine;this.enemies=[];this.spawnTimer=0;this.difficulty=1;this.types={slime:{hp:30,dmg:6,sp:45,r:13,c:'#45d483',state:'idle'},zombie:{hp:55,dmg:11,sp:55,r:15,c:'#6c8a50'},skeleton:{hp:44,dmg:10,sp:48,r:14,c:'#d8d0c2',ranged:true},wolf:{hp:48,dmg:12,sp:105,r:13,c:'#c9e7ff',pack:true},goblin:{hp:50,dmg:13,sp:82,r:14,c:'#72d66a'},bat:{hp:24,dmg:7,sp:125,r:10,c:'#9ca3af',fly:true},boss:{hp:800,dmg:30,sp:55,r:38,c:'#7c3aed',boss:true}};}
  spawn(type,x,y){const t=this.types[type]||this.types.slime;const night=this.engine.systems.weather.isNight()?1.35:1;const e={type,name:type,x,y,vx:0,vy:0,hp:t.hp*this.difficulty*night,max:t.hp*this.difficulty*night,dmg:t.dmg*this.difficulty*night,sp:t.sp,r:t.r,c:t.c,state:'idle',timer:0,cd:0,fly:t.fly,ranged:t.ranged,boss:t.boss,dead:false,patrol:Math.random()<.5?-1:1};this.enemies.push(e);return e;}
  spawnBoss(){if(!this.enemies.some(e=>e.boss))this.spawn('boss',this.engine.systems.player.x+520,this.engine.systems.player.y-60);}
  damageEnemy(e,dmg,status,kb=0){if(status==='burn')e.burn=3;if(status==='freeze')e.freeze=2;if(status==='poison')e.poison=4;e.hp-=dmg;e.vx+=kb;this.engine.ui.hud?.floatText('-'+Math.floor(dmg),e.x,e.y-e.r,'#fff');this.engine.shake(e.boss?.1:.04);if(e.hp<=0)this.kill(e);}
  kill(e){e.dead=true;const inv=this.engine.systems.inventory;const drops={slime:['fiber','berry'],zombie:['fiber','coal'],skeleton:['bone','bow'],wolf:['cooked_meat','fiber'],goblin:['wood','gold'],bat:['coal','crystal'],boss:['obsidian_blade','crystal','gold']};(drops[e.type]||['wood']).forEach(id=>{if(PS.Items[id])inv.add(id,U.irnd(1,e.boss?6:2));});this.engine.systems.player.addXP(e.boss?120:10,'combat');this.engine.systems.crafting?.discoverNearby();if(e.boss)this.engine.toast('🏆 Elite Boss defeated! Mythic tier unlocked.','#ffd166');}
  update(dt){const p=this.engine.systems.player,world=this.engine.systems.world,combat=this.engine.systems.combat,weather=this.engine.systems.weather;this.difficulty=1+p.level*.08+(weather.isNight()?.35:0);this.spawnTimer-=dt;if(this.spawnTimer<=0&&this.enemies.length<28){this.spawnTimer=weather.isNight()?1.8:3.8;const side=Math.random()<.5?-1:1,type=this.pickType(world.biomeAt(Math.floor(p.x/world.tile)));this.spawn(type,p.x+side*U.rnd(430,720),p.y-U.rnd(0,80));}
    for(const e of this.enemies){if(e.dead)continue;e.cd-=dt;e.timer-=dt;if(e.freeze)e.freeze-=dt;if(e.burn){e.burn-=dt;e.hp-=4*dt;if(e.hp<=0){this.kill(e);continue;}}if(e.poison){e.poison-=dt;e.hp-=2*dt;}const d=U.dist(e.x,e.y,p.x,p.y);if(e.hp<e.max*.18&&!e.boss)e.state='flee';else if(d<360||e.boss)e.state='chase';else if(e.timer<=0){e.state=Math.random()<.6?'patrol':'idle';e.timer=U.rnd(1,3);}
      let dir=0;if(e.state==='chase')dir=Math.sign(p.x-e.x);if(e.state==='flee')dir=-Math.sign(p.x-e.x);if(e.state==='patrol')dir=e.patrol;if(e.freeze)dir*=.4;e.vx=U.lerp(e.vx,dir*e.sp,.08);if(e.fly){e.y+=Math.sin(this.engine.time*3+e.x)*20*dt;e.x+=e.vx*dt;}else{e.vy=(e.vy||0)+PS.Config.gravity*dt;e.x+=e.vx*dt;if(world.isSolidAt(e.x+Math.sign(e.vx)*e.r,e.y))e.vx*=-1,e.patrol*=-1;e.y+=e.vy*dt;if(world.isSolidAt(e.x,e.y+e.r)){e.y=Math.floor((e.y+e.r)/world.tile)*world.tile-e.r-1;e.vy=0;}}
      if(d<e.r+22&&e.cd<=0){e.cd=e.boss?.75:1.1;p.damage(e.dmg,e.poison?'poison':'hit');}
      if(e.ranged&&d<420&&e.cd<=0){e.cd=1.8;const n=U.norm(p.x-e.x,p.y-e.y);combat.projectiles.push({x:e.x,y:e.y,vx:n[0]*330,vy:n[1]*330,dmg:e.dmg,life:2,owner:'enemy'});}if(e.boss&&e.cd<=0&&d<520){e.cd=.9;const n=U.norm(p.x-e.x,p.y-e.y);for(let i=-1;i<=1;i++)combat.projectiles.push({x:e.x,y:e.y,vx:n[0]*380+i*80,vy:n[1]*380,dmg:e.dmg*.7,life:2,owner:'enemy',status:'burn'});}}
    this.enemies=this.enemies.filter(e=>!e.dead&&(U.dist(e.x,e.y,p.x,p.y)<1600||e.boss));}
  pickType(b){if(b==='desert')return Math.random()<.5?'skeleton':'goblin';if(b==='snow')return 'wolf';if(b==='swamp')return Math.random()<.5?'slime':'zombie';if(b==='volcano')return Math.random()<.15?'boss':'goblin';if(b==='ocean')return 'bat';return ['slime','zombie','goblin','wolf'][U.irnd(0,3)];}
  serialize(){return{enemies:this.enemies.filter(e=>e.boss)}} deserialize(d){this.enemies=d?.enemies||[];}
}
PS.AISystem=AISystem;
})();
