(function(){
'use strict'; const PS=window.PS;
class BuildingSystem{
  constructor(engine){this.engine=engine;this.selectedItem=null;this.rotation=0;this.destroyMode=false;setTimeout(()=>{const b=document.getElementById('openBuild');if(b)b.onclick=()=>this.openPanel();},0);}
  select(id){this.selectedItem=id;this.destroyMode=false;this.engine.toast('Selected block: '+PS.Items[id].name,'#ffd166');}
  rotate(){this.rotation=(this.rotation+1)%4;this.engine.toast('Rotation '+this.rotation*90+'°','#9db1c4');}
  toggleDestroy(){this.destroyMode=!this.destroyMode;this.engine.toast(this.destroyMode?'Destroy mode':'Build mode',this.destroyMode?'#f05265':'#49d17d');}
  actionAt(wx,wy){const world=this.engine.systems.world,inv=this.engine.systems.inventory,tx=Math.floor(wx/world.tile),ty=Math.floor(wy/world.tile),p=this.engine.systems.player;if(Math.hypot(wx-p.x,wy-p.y)>180)return this.engine.toast('Too far','#ff9f43');if(this.destroyMode){const id=world.getTile(tx,ty);if(id!==0){world.mine(tx,ty,99);this.engine.systems.audio?.play('mine');}return;}if(!this.selectedItem){const s=inv.hotbarSlot();if(s&&PS.Items[s.id].block)this.selectedItem=s.id;}if(!this.selectedItem)return;if(!inv.count(this.selectedItem))return this.engine.toast('Missing block','#f05265');if(world.place(tx,ty,this.selectedItem)){inv.remove(this.selectedItem,1);p.addXP(2,'crafting');this.engine.systems.audio?.play('build');}else this.engine.toast('Cannot place here','#f05265');}
  buildStructure(kind){const p=this.engine.systems.player,w=this.engine.systems.world,inv=this.engine.systems.inventory;const tx=Math.floor(p.x/w.tile),ty=Math.floor(p.y/w.tile);if(kind==='house'){if(!inv.has({wood_wall:20,door:1}))return this.engine.toast('Need 20 wood walls + 1 door','#f05265');inv.take({wood_wall:20,door:1});for(let x=-4;x<=4;x++){w.place(tx+x,ty+2,'wood_wall');w.place(tx+x,ty-3,'wood_wall');}for(let y=-3;y<=2;y++){w.place(tx-4,ty+y,'wood_wall');w.place(tx+4,ty+y,'wood_wall');}w.setTile(tx,ty+2,0);w.place(tx,ty+1,'door');this.engine.toast('House built','#49d17d');}}
  openPanel(){const panel=document.getElementById('panel'),inv=this.engine.systems.inventory;panel.dataset.kind='build';panel.classList.remove('hidden');const blocks=inv.slots.filter(Boolean).filter(s=>PS.Items[s.id]?.block);panel.innerHTML=`<h2>🏗️ Building System</h2><p>Grid placement, rotate, destroy blocks, structures, traps, doors, farms and falling-block physics.</p><div class="toolbar"><button onclick="PS.app.systems.building.toggleDestroy()">${this.destroyMode?'Destroy ON':'Destroy OFF'}</button><button onclick="PS.app.systems.building.rotate()">Rotate</button><button onclick="PS.app.systems.building.buildStructure('house')">Auto House</button></div><h3>Placeable Items</h3>${blocks.map(s=>`<div class="card"><div class="row"><b>${PS.Items[s.id].icon} ${PS.Items[s.id].name} x${s.count}</b><button onclick="PS.app.systems.building.select('${s.id}')">Select</button></div></div>`).join('')||'<p>No placeable blocks in inventory.</p>'}`;}
  update(dt){}
  serialize(){return{selectedItem:this.selectedItem,rotation:this.rotation}} deserialize(d){if(d)Object.assign(this,d);}
}
PS.BuildingSystem=BuildingSystem;
})();
