(function(){
'use strict'; const PS=window.PS,U=PS.Utils;
class HUD{
  constructor(engine){this.engine=engine;this.floaters=[];setTimeout(()=>{const b=document.getElementById('openMap');if(b)b.onclick=()=>this.toggleMapPanel();},0);}
  floatText(msg,x,y,color='#fff'){this.floaters.push({msg,x,y,color,t:1});}
  update(dt){for(const f of this.floaters){f.t-=dt;f.y-=30*dt;}this.floaters=this.floaters.filter(f=>f.t>0);if(this.engine.frame%8)return;const p=this.engine.systems.player,w=this.engine.systems.world,inv=this.engine.systems.inventory,weather=this.engine.systems.weather;const set=(id,val)=>{const el=document.getElementById(id);if(el)el.textContent=val;};const bar=(id,v,c)=>{const el=document.getElementById(id);if(el){el.style.width=U.clamp(v,0,100)+'%';el.style.background=c;}};bar('hpBar',p.stats.health/p.stats.maxHealth*100,'#f05265');bar('hungerBar',p.stats.hunger,'#ffd166');bar('thirstBar',p.stats.thirst,'#4ba3ff');bar('staminaBar',p.stats.stamina,'#49d17d');bar('tempBar',U.clamp((p.stats.temperature+20)/70*100,0,100),p.stats.temperature>35?'#ff9f43':p.stats.temperature<0?'#6ee7ff':'#49d17d');bar('oxygenBar',p.stats.oxygen,'#6ee7ff');set('hpText',Math.floor(p.stats.health));set('hungerText',Math.floor(p.stats.hunger));set('thirstText',Math.floor(p.stats.thirst));set('staminaText',Math.floor(p.stats.stamina));set('tempText',Math.floor(p.stats.temperature));set('oxygenText',Math.floor(p.stats.oxygen));set('levelText',p.level);set('biomeText',w.biomeName(w.biomeAt(Math.floor(p.x/w.tile))));set('layerText',['Surface','Underground','Deep Caves'][w.currentLayer]);set('weatherText',weather.type);set('timeText',weather.timeString());set('weightText',Math.floor(inv.weight())+'/'+Math.floor(inv.maxWeight()));set('fpsBadge',this.engine.fps+' FPS');this.renderHotbar();}
  renderHotbar(){const inv=this.engine.systems.inventory,box=document.getElementById('hotbar');if(!box)return;box.innerHTML=inv.hotbar.map((slot,i)=>{const s=inv.slots[slot],it=s?PS.Items[s.id]:null;return`<div class="hotSlot ${i===inv.selectedHotbar?'active':''}" data-hot="${i}">${it?it.icon:''}<small>${s?s.count:''}</small></div>`;}).join('');box.querySelectorAll('.hotSlot').forEach(el=>el.onclick=()=>{inv.selectedHotbar=+el.dataset.hot;this.renderHotbar();});}
  draw(ctx){for(const f of this.floaters){ctx.save();ctx.globalAlpha=f.t;ctx.fillStyle=f.color;ctx.font='12px monospace';ctx.fillText(f.msg,f.x-this.engine.camera.x,f.y-this.engine.camera.y);ctx.restore();}}
  toggleMapPanel(){const panel=document.getElementById('panel');if(!panel.classList.contains('hidden')&&panel.dataset.kind==='map'){panel.classList.add('hidden');return;}panel.dataset.kind='map';panel.classList.remove('hidden');panel.innerHTML=`<h2>🗺️ Map System</h2><p>Biome colors, player marker and cave layer toggle.</p><div class="toolbar"><button onclick="PS.app.systems.world.currentLayer=0">Surface</button><button onclick="PS.app.systems.world.currentLayer=1">Underground</button><button onclick="PS.app.systems.world.currentLayer=2">Deep Caves</button></div><p class="muted">Mini-map is rendered bottom-right. Current layer changes terrain generation and cave darkness.</p>`;}
}
PS.HUD=HUD;
})();
