(function(){
'use strict'; const PS=window.PS,U=PS.Utils;
class InputSystem{
  constructor(engine){this.engine=engine;this.keys={};this.moveX=0;this.moveY=0;this.jump=false;this.run=false;this.aim={x:1,y:0};this.pointer={x:0,y:0,wx:0,wy:0,down:false};this.leftJoy={x:0,y:0};this.rightJoy={x:0,y:0};this.bind();}
  bind(){addEventListener('keydown',e=>{this.keys[e.code]=true;if(e.repeat)return;const inv=this.engine.systems.inventory;if(e.code.startsWith('Digit')){const n=parseInt(e.code.slice(5),10);if(n>=1&&n<=9)inv.selectedHotbar=n-1;}if(e.code==='KeyI')this.engine.ui.inventoryUI.toggle();if(e.code==='KeyC')this.engine.ui.craftingUI.toggle();if(e.code==='KeyM')this.engine.ui.hud.toggleMapPanel();if(e.code==='KeyB')this.engine.systems.building.toggleDestroy();if(e.code==='KeyR')this.engine.systems.building.rotate();if(e.code==='KeyE')this.interact();if(e.code==='KeyF'||e.code==='Space')this.engine.systems.combat.attack();if(e.code==='ShiftLeft'||e.code==='ShiftRight')this.engine.systems.combat.dodge();if(e.code==='KeyQ')inv.useHotbar();if(e.code==='F5')this.engine.systems.save.save();});addEventListener('keyup',e=>{this.keys[e.code]=false;});const c=this.engine.canvas;c.addEventListener('pointermove',e=>this.pointerMove(e));c.addEventListener('pointerdown',e=>{c.setPointerCapture?.(e.pointerId);this.pointerMove(e);this.pointer.down=true;if(e.button===2||this.engine.systems.building.destroyMode)this.interact();else if(this.engine.systems.building.selectedItem)this.engine.systems.building.actionAt(this.pointer.wx,this.pointer.wy);else this.engine.systems.combat.attack();});c.addEventListener('pointerup',()=>this.pointer.down=false);c.addEventListener('contextmenu',e=>e.preventDefault());}
  pointerMove(e){const r=this.engine.canvas.getBoundingClientRect();this.pointer.x=e.clientX-r.left;this.pointer.y=e.clientY-r.top;this.pointer.wx=this.engine.camera.x+this.pointer.x;this.pointer.wy=this.engine.camera.y+this.pointer.y;const p=this.engine.systems.player;if(p){const n=U.norm(this.pointer.wx-p.x,this.pointer.wy-p.y);this.aim={x:n[0],y:n[1]};}}
  interact(){const p=this.engine.systems.player,w=this.engine.systems.world,inv=this.engine.systems.inventory;const wx=this.pointer.wx||p.x+p.facing*55,wy=this.pointer.wy||p.y;const tx=Math.floor(wx/w.tile),ty=Math.floor(wy/w.tile);if(this.engine.systems.farming.harvestAt(tx,ty)){this.engine.systems.audio?.play('eat');return;}if(this.keys.KeyV){this.engine.systems.farming.waterAt(tx,ty);return;}if(this.engine.systems.building.destroyMode){this.engine.systems.building.actionAt(wx,wy);return;}const id=w.getTile(tx,ty);if(id!==0&&id!==8){const tool=inv.equipment.weapon||inv.hotbarSlot();const it=tool?PS.Items[tool.id]:null;w.mine(tx,ty,it?.harvest||1);return;}const s=inv.hotbarSlot();if(s&&PS.Items[s.id]?.block)this.engine.systems.building.actionAt(wx,wy);}
  update(){this.moveX=(this.keys.KeyD||this.keys.ArrowRight?1:0)-(this.keys.KeyA||this.keys.ArrowLeft?1:0)+this.leftJoy.x;this.moveY=(this.keys.KeyS||this.keys.ArrowDown?1:0)-(this.keys.KeyW||this.keys.ArrowUp?1:0)+this.leftJoy.y;this.jump=!!(this.keys.KeyW||this.keys.ArrowUp||this.keys.Space||this.leftJoy.y<-0.55);this.run=!!(this.keys.ControlLeft||this.keys.ControlRight);if(Math.abs(this.rightJoy.x)+Math.abs(this.rightJoy.y)>.15)this.aim={x:this.rightJoy.x,y:this.rightJoy.y};}
}
PS.InputSystem=InputSystem;
})();
