(function(){
'use strict'; const PS=window.PS;
class MobileControls{
  constructor(engine){this.engine=engine;this.root=document.getElementById('mobileControls');this.build();}
  build(){this.root.innerHTML=`<div class="joy left" id="joyLeft"><div class="stick"></div></div><div class="joy right" id="joyRight"><div class="stick"></div></div><div class="touchButtons"><button id="mAttack" class="danger">ATT</button><button id="mDodge">DOD</button><button id="mAction" class="primary">ACT</button><button id="mInv">INV</button><button id="mCraft">CRF</button><button id="mBuild">BLD</button></div>`;this.bindJoy('joyLeft','leftJoy');this.bindJoy('joyRight','rightJoy');document.getElementById('mAttack').onclick=e=>{this.pulse(e);this.engine.systems.combat.attack();};document.getElementById('mDodge').onclick=e=>{this.pulse(e);this.engine.systems.combat.dodge();};document.getElementById('mAction').onclick=e=>{this.pulse(e);this.engine.systems.input.interact();};document.getElementById('mInv').onclick=()=>this.engine.ui.inventoryUI.toggle();document.getElementById('mCraft').onclick=()=>this.engine.ui.craftingUI.toggle();document.getElementById('mBuild').onclick=()=>this.engine.systems.building.toggleDestroy();}
  bindJoy(id,target){const el=document.getElementById(id),stick=el.querySelector('.stick'),input=this.engine.systems.input;let active=false,cx=0,cy=0;const move=e=>{if(!active)return;let dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy),m=40;if(l>m){dx=dx/l*m;dy=dy/l*m;}stick.style.left=40+dx+'px';stick.style.top=40+dy+'px';input[target]={x:dx/m,y:dy/m};};el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);active=true;const r=el.getBoundingClientRect();cx=r.left+63;cy=r.top+63;move(e);});el.addEventListener('pointermove',move);el.addEventListener('pointerup',()=>{active=false;input[target]={x:0,y:0};stick.style.left='40px';stick.style.top='40px';});}
  pulse(e){const p=document.createElement('i');p.className='hapticPulse';p.style.left=e.clientX-25+'px';p.style.top=e.clientY-25+'px';p.style.width=p.style.height='50px';document.body.appendChild(p);setTimeout(()=>p.remove(),380);}
}
PS.MobileControls=MobileControls;
})();
