(function(){
'use strict'; const PS=window.PS,U=PS.Utils;
class RenderSystem{
  constructor(engine){this.engine=engine;this.menuTick=0;}
  updateCamera(dt){const e=this.engine,p=e.systems.player;if(!p)return;const targetX=p.x-e.viewW*.45,targetY=p.y-e.viewH*.52;e.camera.x=U.lerp(e.camera.x,targetX,.09);e.camera.y=U.lerp(e.camera.y,targetY,.09);if(e.camera.shake>0)e.camera.shake=Math.max(0,e.camera.shake-dt*1.8);}
  draw(){const e=this.engine,ctx=e.ctx;ctx.save();ctx.scale(e.dpr,e.dpr);ctx.clearRect(0,0,e.viewW,e.viewH);if(e.mode==='splash'||e.mode==='menu')this.drawMenuBackground();else this.drawGame();ctx.restore();}
  sx(x){return x-this.engine.camera.x;} sy(y){return y-this.engine.camera.y;} rect(x,y,w,h,c){const ctx=this.engine.ctx;ctx.fillStyle=c;ctx.fillRect(x|0,y|0,w|0,h|0);}
  drawMenuBackground(){const e=this.engine,ctx=e.ctx,vw=e.viewW,vh=e.viewH;this.menuTick+=.016;ctx.fillStyle='#07111f';ctx.fillRect(0,0,vw,vh);for(let l=0;l<4;l++){ctx.fillStyle=['#102033','#193a50','#245b35','#357b4b'][l];const y=vh*(.35+l*.14)+Math.sin(this.menuTick+l)*18;ctx.beginPath();ctx.moveTo(0,vh);for(let x=0;x<=vw+40;x+=40)ctx.lineTo(x,y+Math.sin(x*.01+this.menuTick+l)*25);ctx.lineTo(vw,vh);ctx.fill();}for(let i=0;i<70;i++){const x=(i*97+this.menuTick*20*(i%3+1))%vw,y=(i*53)%vh;ctx.fillStyle=i%5?'#ffffff18':'#49d17d55';ctx.fillRect(x,y,3,3);}}
  drawGame(){const e=this.engine,ctx=e.ctx,w=e.systems.world,weather=e.systems.weather,p=e.systems.player;this.updateCamera(.016);let shakeX=0,shakeY=0;if(e.camera.shake){shakeX=U.rnd(-10,10)*e.camera.shake;shakeY=U.rnd(-10,10)*e.camera.shake;}ctx.save();ctx.translate(shakeX,shakeY);this.drawParallax();this.drawTiles();this.drawDrops();this.drawCrops();this.drawEnemies();this.drawProjectiles();this.drawPlayer();this.drawLighting();this.drawWeather();this.drawVignette();this.drawMiniMap();ctx.restore();}
  drawParallax(){const e=this.engine,ctx=e.ctx,weather=e.systems.weather,vw=e.viewW,vh=e.viewH;const t=(e.dayTime%(60*24))/(60*24),night=weather.isNight();const sky=night?'#081027':t<.25?'#f5a45b':t>.75?'#29304f':'#69b7ff';ctx.fillStyle=sky;ctx.fillRect(0,0,vw,vh);ctx.fillStyle=night?'#dce7ff':'#fff4a3';ctx.beginPath();ctx.arc(vw*(night?.78:.72),vh*(night?.18:.14),night?18:32,0,Math.PI*2);ctx.fill();for(let i=0;i<2;i++){ctx.fillStyle=i?'#1e3a4f':'#294d63';const off=-(this.engine.camera.x*(.08+i*.05))%300;ctx.beginPath();ctx.moveTo(-300+off,vh*.56);for(let x=-300+off;x<vw+300;x+=80)ctx.lineTo(x,vh*.42+Math.sin(x*.01+i)*40);ctx.lineTo(vw+300,vh);ctx.lineTo(-300,vh);ctx.fill();}}
  drawTiles(){const e=this.engine,w=e.systems.world,ctx=e.ctx,T=w.tile;const x0=Math.floor(e.camera.x/T)-1,x1=Math.floor((e.camera.x+e.viewW)/T)+1,y0=Math.floor(e.camera.y/T)-1,y1=Math.floor((e.camera.y+e.viewH)/T)+1;for(let ty=y0;ty<=y1;ty++)for(let tx=x0;tx<=x1;tx++){const id=w.getTile(tx,ty),d=w.tileDefs[id];if(!d||id===0)continue;const x=tx*T-e.camera.x,y=ty*T-e.camera.y;ctx.fillStyle=d.c||'#999';ctx.fillRect(x|0,y|0,T,T);ctx.fillStyle='rgba(255,255,255,.06)';ctx.fillRect(x+2,y+2,T-4,3);ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(x,y+T-4,T,4);if(d.liquid){ctx.globalAlpha=.72;ctx.fillStyle='#3fa7ff';ctx.fillRect(x,y+5,T,T-5);ctx.globalAlpha=1;}}}
  drawDrops(){const e=this.engine,w=e.systems.world;for(const d of w.dropped){const it=PS.Items[d.id]||{icon:'?'};const x=this.sx(d.x),y=this.sy(d.y);if(x<-30||x>e.viewW+30||y<-30||y>e.viewH+30)continue;this.rect(x-8,y-8,16,16,'#0008');e.ctx.font='15px monospace';e.ctx.fillText(it.icon,x-8,y+5);}}
  drawCrops(){const e=this.engine,w=e.systems.world;for(const c of e.systems.farming.crops){const x=c.x*w.tile-e.camera.x,y=c.y*w.tile-e.camera.y;this.rect(x+9,y+24-c.stage*6,14,8+c.stage*6,['#6b4529','#49d17d','#70e000','#ffd166'][c.stage]);}}
  drawEnemies(){const e=this.engine,ctx=e.ctx;for(const en of e.systems.ai.enemies){const x=this.sx(en.x),y=this.sy(en.y);if(x<-80||x>e.viewW+80||y<-80||y>e.viewH+80)continue;ctx.fillStyle=en.c;ctx.fillRect((x-en.r)|0,(y-en.r)|0,en.r*2,en.r*2);ctx.fillStyle='#111';ctx.fillRect(x-5,y-4,4,4);ctx.fillRect(x+3,y-4,4,4);this.hpbar(x,y-en.r-10,en.boss?90:36,en.hp/en.max,en.boss?'#f05265':'#ff7a85');}}
  drawProjectiles(){const c=this.engine.systems.combat;for(const q of c.projectiles)this.rect(this.sx(q.x)-3,this.sy(q.y)-3,6,6,q.owner==='player'?'#ffd166':'#b56cff');for(const s of c.slashes){const ctx=this.engine.ctx;ctx.globalAlpha=.35;ctx.strokeStyle=s.crit?'#ffd166':'#fff';ctx.lineWidth=8;ctx.beginPath();ctx.arc(this.sx(s.x),this.sy(s.y),s.r,Math.atan2(s.ay,s.ax)-.8,Math.atan2(s.ay,s.ax)+.8);ctx.stroke();ctx.globalAlpha=1;}}
  drawPlayer(){const p=this.engine.systems.player,x=this.sx(p.x),y=this.sy(p.y),ctx=this.engine.ctx;if(p.invuln>0&&Math.floor(this.engine.time*20)%2)return;ctx.fillStyle=p.anim==='run'?'#70e0ff':'#4ba3ff';ctx.fillRect(x-10,y-17,20,30);ctx.fillStyle='#f2c28b';ctx.fillRect(x-7,y-28,14,12);ctx.fillStyle='#fff';ctx.fillRect(x+p.facing*11-3,y-9,6,6);}
  drawLighting(){const e=this.engine;if(!e.settings.showLighting)return;const ctx=e.ctx,w=e.systems.world,weather=e.systems.weather;const night=weather.isNight();const alpha=w.currentLayer>0?.62:night?.38:.04;if(alpha){ctx.fillStyle=`rgba(0,0,20,${alpha})`;ctx.fillRect(0,0,e.viewW,e.viewH);}ctx.globalCompositeOperation='destination-out';const p=e.systems.player;this.light(this.sx(p.x),this.sy(p.y),w.currentLayer>0?150:80);const x0=Math.floor(e.camera.x/w.tile)-2,x1=Math.floor((e.camera.x+e.viewW)/w.tile)+2,y0=Math.floor(e.camera.y/w.tile)-2,y1=Math.floor((e.camera.y+e.viewH)/w.tile)+2;for(let ty=y0;ty<=y1;ty++)for(let tx=x0;tx<=x1;tx++){const d=w.tileDefs[w.getTile(tx,ty)];if(d&&d.light)this.light(tx*w.tile-e.camera.x+16,ty*w.tile-e.camera.y+16,d.light*36);}ctx.globalCompositeOperation='source-over';}
  light(x,y,r){const ctx=this.engine.ctx,g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(255,255,255,.9)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
  drawWeather(){const e=this.engine,ctx=e.ctx,w=e.systems.weather;if(w.type==='clear')return;ctx.strokeStyle=w.type==='snow'?'#e6fbff':w.type==='heatwave'?'#ff9f4344':'#7cc7ff88';ctx.lineWidth=w.type==='storm'?2:1;const count=e.lowEnd?35:90;for(let i=0;i<count;i++){const x=(i*83+e.time*160*(w.wind>0?1:-1))%e.viewW,y=(i*47+e.time*260)%e.viewH;if(w.type==='snow')ctx.strokeRect(x,y,3,3);else{ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w.wind*.08,y+12);ctx.stroke();}}}
  drawVignette(){const e=this.engine,ctx=e.ctx,g=ctx.createRadialGradient(e.viewW/2,e.viewH/2,80,e.viewW/2,e.viewH/2,Math.max(e.viewW,e.viewH)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.38)');ctx.fillStyle=g;ctx.fillRect(0,0,e.viewW,e.viewH);}
  drawMiniMap(){const e=this.engine,ctx=e.ctx,w=e.systems.world,p=e.systems.player,x=e.viewW-150,y=e.viewH-150;ctx.fillStyle='#0009';ctx.fillRect(x,y,136,136);ctx.strokeStyle='#ffffff33';ctx.strokeRect(x,y,136,136);for(let ix=-20;ix<=20;ix+=2){const b=w.biomeAt(Math.floor(p.x/w.tile)+ix);ctx.fillStyle=w.biomeColor(b);ctx.fillRect(x+68+ix*3,y+92,6,8);}ctx.fillStyle='#fff';ctx.fillRect(x+66,y+66,5,5);}
  hpbar(x,y,w,p,c){this.rect(x-w/2,y,w,4,'#000a');this.rect(x-w/2,y,w*Math.max(0,Math.min(1,p)),4,c);}
}
PS.RenderSystem=RenderSystem;
})();
