(function(){
'use strict'; const PS=window.PS,U=PS.Utils,C=PS.Config;
class WorldSystem{
  constructor(engine){this.engine=engine;this.seed=133742;this.chunkSize=C.chunkTiles;this.tile=C.tile;this.chunks=new Map();this.edits=new Map();this.currentLayer=0;this.tileDefs=this.makeTileDefs();this.dropped=[];}
  makeTileDefs(){return{0:{id:0,n:'Air',solid:false},1:{id:1,n:'Grass',solid:true,drop:'dirt_block',hp:2,c:'#3b8b4e'},2:{id:2,n:'Dirt',solid:true,drop:'dirt_block',hp:2,c:'#6b4529'},3:{id:3,n:'Stone',solid:true,drop:'stone',hp:4,c:'#676f7c'},4:{id:4,n:'Sand',solid:true,drop:'stone',hp:2,c:'#d6a24b',fall:true},5:{id:5,n:'Snow',solid:true,drop:'stone',hp:2,c:'#dff8ff'},6:{id:6,n:'Mud',solid:true,drop:'dirt_block',hp:2,c:'#4d6334'},7:{id:7,n:'Basalt',solid:true,drop:'obsidian',hp:6,c:'#2a2020'},8:{id:8,n:'Water',solid:false,liquid:true,c:'#2f7ed8'},9:{id:9,n:'Wood',solid:true,drop:'wood',hp:3,c:'#7a4a2a'},10:{id:10,n:'Leaves',solid:false,drop:'fiber',hp:1,c:'#3e9d53'},11:{id:11,n:'Coal',solid:true,drop:'coal',hp:4,c:'#22252c'},12:{id:12,n:'Iron',solid:true,drop:'iron',hp:5,c:'#9fa8b6'},13:{id:13,n:'Gold',solid:true,drop:'gold',hp:5,c:'#ffd166'},14:{id:14,n:'Crystal',solid:true,drop:'crystal',hp:6,c:'#7de7ff',light:2},15:{id:15,n:'Torch',solid:false,drop:'torch',hp:1,c:'#ff9f43',light:5},16:{id:16,n:'Wood Wall',solid:true,drop:'wood_wall',hp:5,c:'#8b5a2b'},17:{id:17,n:'Stone Wall',solid:true,drop:'stone_wall',hp:8,c:'#858d98'},18:{id:18,n:'Trap',solid:false,drop:'trap',hp:4,c:'#d8d0c2',trap:true},19:{id:19,n:'Farm',solid:true,drop:'farm_plot',hp:2,c:'#5b3b24',farm:true},20:{id:20,n:'Workbench',solid:true,drop:'workbench',hp:8,c:'#a46a3d',station:'workbench'},21:{id:21,n:'Furnace',solid:true,drop:'furnace',hp:10,c:'#5b6470',station:'furnace'},22:{id:22,n:'Anvil',solid:true,drop:'anvil',hp:10,c:'#3f4652',station:'anvil'}};}
  biomeAt(tx){const x=tx*this.tile,d=Math.abs(tx),w=Math.sin(tx*.05+this.seed)*20;if(d<70+w)return'grasslands';if(tx>70&&tx<160)return'forest';if(tx>=160&&tx<260)return'desert';if(tx<-70&&tx>-170)return'snow';if(tx<=-170&&tx>-280)return'swamp';if(tx>260)return'volcano';if(tx<-280)return'ocean';return'forest';}
  biomeName(b){return{grasslands:'Grasslands',forest:'Forest',desert:'Desert',snow:'Snow',swamp:'Swamp',volcano:'Volcano',ocean:'Ocean'}[b]||b;}
  biomeColor(b){return{grasslands:'#3b8b4e',forest:'#236b37',desert:'#bd873a',snow:'#bde7f1',swamp:'#384f2d',volcano:'#4b2424',ocean:'#2f7ed8'}[b]||'#3b8b4e';}
  surfaceHeight(tx){return 18+Math.floor(Math.sin(tx*.045+this.seed)*4+Math.sin(tx*.011)*9);}
  key(cx,cy,l=this.currentLayer){return l+':'+cx+','+cy;}
  getChunk(cx,cy,l=this.currentLayer){const k=this.key(cx,cy,l);if(this.chunks.has(k))return this.chunks.get(k);const tiles=new Uint8Array(this.chunkSize*this.chunkSize);for(let y=0;y<this.chunkSize;y++)for(let x=0;x<this.chunkSize;x++){const tx=cx*this.chunkSize+x,ty=cy*this.chunkSize+y;tiles[y*this.chunkSize+x]=this.genTile(tx,ty,l);}const ch={cx,cy,l,tiles,last:0};this.chunks.set(k,ch);return ch;}
  genTile(tx,ty,l){const b=this.biomeAt(tx),h=this.surfaceHeight(tx);if(l===1){if(ty<4)return 0;if(U.rand2(tx,ty,this.seed+9)<.09)return 0;if(ty>18&&U.rand2(tx,ty,this.seed+4)<.04)return 11;if(ty>22&&U.rand2(tx,ty,this.seed+5)<.035)return 12;return 3;}if(l===2){if(U.rand2(tx,ty,this.seed+33)<.14)return 0;if(U.rand2(tx,ty,this.seed+34)<.035)return 14;if(U.rand2(tx,ty,this.seed+35)<.035)return 13;return b==='volcano'?7:3;}if(b==='ocean'&&ty>h-3&&ty<h+5)return 8;if(ty<h)return 0;if(ty===h){if(b==='desert')return 4;if(b==='snow')return 5;if(b==='swamp')return 6;if(b==='volcano')return 7;return 1;}if(ty<h+5)return b==='desert'?4:b==='swamp'?6:2;if(U.rand2(tx,ty,this.seed+7)<.035)return 11;if(U.rand2(tx,ty,this.seed+8)<.025)return 12;if(b==='volcano'&&U.rand2(tx,ty,this.seed+10)<.035)return 14;return 3;}
  local(tx,ty){const cs=this.chunkSize,cx=Math.floor(tx/cs),cy=Math.floor(ty/cs),lx=((tx%cs)+cs)%cs,ly=((ty%cs)+cs)%cs;return{cx,cy,lx,ly,i:ly*cs+lx};}
  getTile(tx,ty,l=this.currentLayer){const e=this.edits.get(l+':'+tx+','+ty);if(e!==undefined)return e;const a=this.local(tx,ty),ch=this.getChunk(a.cx,a.cy,l);ch.last=this.engine.frame;return ch.tiles[a.i];}
  setTile(tx,ty,id,l=this.currentLayer){this.edits.set(l+':'+tx+','+ty,id);const a=this.local(tx,ty),ch=this.getChunk(a.cx,a.cy,l);ch.tiles[a.i]=id;}
  tileAtWorld(x,y,l=this.currentLayer){return this.getTile(Math.floor(x/this.tile),Math.floor(y/this.tile),l);}
  isSolidAt(x,y,l=this.currentLayer){const id=this.tileAtWorld(x,y,l),d=this.tileDefs[id];return !!(d&&d.solid);}
  stationNear(x,y,station){const r=4;for(let tx=Math.floor(x/this.tile)-r;tx<=Math.floor(x/this.tile)+r;tx++)for(let ty=Math.floor(y/this.tile)-r;ty<=Math.floor(y/this.tile)+r;ty++){const d=this.tileDefs[this.getTile(tx,ty)];if(d&&d.station===station)return true;}return station==='hand';}
  mine(tx,ty,power=1){const id=this.getTile(tx,ty);const d=this.tileDefs[id];if(!d||id===0||d.liquid)return null;const hp=d.hp||2;const k='hp:'+this.currentLayer+':'+tx+','+ty;let left=(this.edits.get(k)||hp)-power;if(left>0){this.edits.set(k,left);return null;}this.edits.delete(k);this.setTile(tx,ty,0);if(d.drop)this.engine.systems.inventory.add(d.drop,1);this.engine.systems.player.addXP(2,'mining');this.engine.systems.audio?.play('mine');return d.drop;}
  place(tx,ty,itemId){if(this.getTile(tx,ty)!==0)return false;const it=PS.Items[itemId];const map={torch:15,dirt_block:2,wood_wall:16,stone_wall:17,trap:18,farm_plot:19,workbench:20,furnace:21,anvil:22};const id=map[itemId]||(it&&it.block==='generatedBlock'?16:0);if(!id)return false;this.setTile(tx,ty,id);return true;}
  spawnDrops(stacks,x,y){stacks.forEach((s,i)=>this.dropped.push({id:s.id,count:s.count,x:x+PS.Utils.rnd(-45,45),y:y-20- i*3,vx:PS.Utils.rnd(-60,60),vy:PS.Utils.rnd(-180,-80),t:0}));}
  update(dt){if(this.engine.lowEnd&&this.engine.frame%4!==0)return;const p=this.engine.systems.player,inv=this.engine.systems.inventory;for(const d of this.dropped){d.t+=dt;d.vy+=PS.Config.gravity*.55*dt;d.x+=d.vx*dt;d.y+=d.vy*dt;if(this.isSolidAt(d.x,d.y+8)){d.vy*=-.18;d.vx*=.75;}if(p&&PS.Utils.dist(d.x,d.y,p.x,p.y)<42){inv.add(d.id,d.count);d.pick=true;}}this.dropped=this.dropped.filter(d=>!d.pick&&d.t<900);this.physicsLite();this.unloadFar();}
  physicsLite(){const p=this.engine.systems.player;if(!p)return;const cx=Math.floor(p.x/this.tile/this.chunkSize),cy=Math.floor(p.y/this.tile/this.chunkSize);for(let tx=(cx*this.chunkSize)-6;tx<(cx*this.chunkSize)+this.chunkSize+6;tx++)for(let ty=(cy*this.chunkSize)-4;ty<(cy*this.chunkSize)+this.chunkSize+6;ty++){const id=this.getTile(tx,ty),d=this.tileDefs[id];if(d&&d.fall&&this.getTile(tx,ty+1)===0){this.setTile(tx,ty+1,id);this.setTile(tx,ty,0);}}}
  unloadFar(){const p=this.engine.systems.player;if(!p)return;const pcx=Math.floor(p.x/this.tile/this.chunkSize),pcy=Math.floor(p.y/this.tile/this.chunkSize);for(const [k,ch] of this.chunks){if(Math.abs(ch.cx-pcx)>5||Math.abs(ch.cy-pcy)>4)this.chunks.delete(k);}}
  serialize(){return{seed:this.seed,currentLayer:this.currentLayer,edits:[...this.edits.entries()],dropped:this.dropped};}
  deserialize(d){if(!d)return;this.seed=d.seed||this.seed;this.currentLayer=d.currentLayer||0;this.edits=new Map(d.edits||[]);this.dropped=d.dropped||[];this.chunks.clear();}
}
PS.WorldSystem=WorldSystem;
})();
